import type { Metadata } from 'next';
import { Open_Sans, Geist_Mono } from 'next/font/google';
import './globals.css';
import QueryClientProviderComponent from '@/components/provider/query-client';

const geistSans = Open_Sans({
  variable: '--font-geist-',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Poké-base',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryClientProviderComponent>{children}</QueryClientProviderComponent>
      </body>
    </html>
  );
}

